apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-0dke
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0075-tenant/tkrw-pr712-0075-0075-app/devfile-sample-0dke@sha256:77ad6adbd6f23afd308847f01a34c6bc9d1863a8536e67e502b25df8cb85996b
        name: my-nodejs
        resources: {}
status: {}
